### ISSUE TITLE
Font issues

### ISSUE THREAD

**Issue by FalcoGer** [dresswithpockets/tunician#1]
The font is too big. You can hardly fit any 3 words in. Also the difference between the gray and the white is too small, I suggest stronger lines for the filled in ones.

**Comment by dresswithpockets** [comment]
Hey @FalcoGer ! thanks for the feedback; however, im taking a break from tunic and maintaining this repo. Until i come back to maintaining this project, I recommend checking out https://konotyran.github.io/tunic/index.html if you havent already!
